flowchart TD
    A[Request DTO]
    B[Domain Model]

    A -->|Übersetzung| B

    classDef box fill:#E0E0E0,stroke-width:0px,color:#393E46;

    class A,B box;

    linkStyle default stroke:#357edd,stroke-width:2px;
